config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :welcome, only: [:index]
  resources :home, only: [:index]
  get 'drugs/search', to: 'drugs#search_by_name'
  get 'drugs/search-name', to: 'drugs#search_by_name'
  get 'drugs/search-usage', to: 'drugs#search_by_usage'
  resources :drugs, only: [:index, :show], param: :name
  get 'profile', to: 'profile#show'
  resource :status, controller: :status, only: [:create]

  get '/auth/twitter', as: :login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      resources :searches, only: [:index, :create], defaults: { format: :json }
      resources :drugs, only: [:index, :show], param: :name, defaults: { format: :json }
      get 'drugs/letter_match/:letter', to: 'drugs#letter_match', defaults: { format: :json }
    end
  end

  get '*path', to: 'home#index'
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :searches

  def self.populate_page
    starts_with_query(:letter => "A")
  end

  def self.starts_with_query(params)
    letter = params[:letter].capitalize
    Drug.where("name like ?", "#{letter}%")
  end

  def slug
    name
  end
end

app/models/recent_searches.rb
class RecentSearches
  def initialize(current_user)
    @current_user = current_user
  end

  def display
    if @current_user && @current_user.search_count_greater_than_6
      @current_user.recent_searches
    else
      Search.recent
    end
  end
end

app/models/response_parser.rb
class ResponseParser
  attr_accessor :response

  def initialize(response)
    @response = response
  end

  def nursing_mothers
    confirm_response(@response[:nursing_mothers]).first
  end

  def description
    confirm_response(@response[:description]).first
  end

  def substance_name
    confirm_response(@response[:openfda][:substance_name]).first
  end

  def manufacturer_name
    confirm_response(@response[:openfda][:manufacturer_name]).first
  end

  def dosage
    confirm_response(@response[:dosage_and_administration]).first
  end

  def usage
    confirm_response(@response[:indications_and_usage]).first
  end

  def confirm_response(call)
    return ["No data to display"] if call == nil
    return call.first ? call : ["No data to display"]
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  belongs_to :drug

  validates_uniqueness_of :drug_id

  def self.recent
    order(:updated_at).take(6)
  end

  def drug_name
    drug.name
  end
end

app/models/tweeter.rb
class Tweeter
  def self.update(params, current_user)
    tweet = params[:tweet]
    current_user.tweet(tweet)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :searches

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end

  def twitter_service
    @twitter_service ||= TwitterService.new(self).client
  end

  def twitter_user
    @twitter_user ||= twitter_service.user
  end

  def profile_photo
    twitter_user.profile_image_uri_https(:original)
  end

  def name
    twitter_user.name
  end

  def handle
    twitter_user.screen_name
  end

  def tweet(tweet)
    twitter_service.update(tweet)
  end

  def breastfeeding_timeline
    twitter_service.search("breastfeeding",
                           result_type: "recent",
                           since: (Time.now-2.weeks).to_date).take(10)
  end

  def search_count_greater_than_6
    searches.count > 6
  end

  def recent_searches
    searches.order(:updated_at).take(6)
  end
end

app/controllers/api/v1/drugs_controller.rb
class Api::V1::DrugsController < ApplicationController
  respond_to :json

  def index
    respond_with Drug.all
  end

  def show
    respond_with find_drug
  end

  def letter_match
    respond_with Drug.starts_with_query(strong_params)
  end

  private

  def find_drug
    name = params[:name].titleize
    Drug.find_by(name: name)
  end

  def strong_params
    params.permit(:id, :name, :letter)
  end
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < ApplicationController
  respond_to :json

  def index
    respond_with Search.all
  end

  def create
    if drug = Drug.find_by(name: strong_params[:value].titleize)
      search = current_user.searches.new(drug_id: drug.id)
      search.save
    end
    render nothing: true
  end

  private

  def strong_params
    params.permit(:id, :value, :current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user, :current_date

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def current_date
    Time.new.strftime('%D')
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def index
    @drugs = Drug.populate_page
  end

  def show
    @drug_lact_med = Drug.find_by(name: params[:name])
    @drug_fda      = OpenFdaService.new.drugs_by_name(params[:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @searches = RecentSearches.new(current_user).display
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end
end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to home_index_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def create
    Tweeter.update(params, current_user)
    redirect_to profile_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cache_key_for(model_class, label="")
    prefix       = model_class.to_s.downcase.pluralize
    last_updated = model_class.maximum(:updated_at)
    count        = model_class.count
    [prefix, label, last_updated, count].join("-")
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drugs/index.html.erb
<% cache cache_key_for(Drug, "index") do %>
  <div class="filter margin-top-80">
    <h1>All Medications</h1>
  </div>
  <%= render partial: 'shared/drugs_by_letter' %>
  <div id="drug-data" class="clearfix">
    <%= render partial: 'shared/lact_med_reference' %>
    <%= render partial: 'shared/drug_index_summary' %>
  </div>
<% end %>

app/views/drugs/search.html.erb
<div id="w">
  <h1>Medication Search</h1>
  <p>Enter the drug name below.</p>

  <input type="text" name="drug-name" id="drug-name" placeholder="Sertraline">

  <a id="search-submit" class="waves-effect waves-light btn">Search</a>

  <!-- <a href="#" id="search-submit">Pull User Data</a> -->

  <div id="drug-data" class="clearfix"></div>
</div>

app/views/drugs/search_by_name.html.erb
<% cache("drug-search-name") do %>
  <div id="name-search" class="margin-top-80">
    <h1>Search by Drug Name</h1>
    <p>Enter the name of the medication below.</p>
    <input type="text" name="drug-name" id="drug-name" placeholder="Amoxicillin, Sertraline, etc.">
    <a id="search-submit" class="cyan lighten-2 search-by-name waves-effect waves-light btn">Search</a>
    <div id="drug-data" class="clearfix"></div>
  </div>
<% end %>

app/views/drugs/search_by_usage.html.erb
<% cache("drug-search-usage") do %>
  <div id="usage-search" class="margin-top-80">
    <h1>Search by Usage or Indictation</h1>
    <p>In one word, describe your ailment below.</p>
    <input type="text" name="drug-usage" id="drug-usage" placeholder="Migraine, anxiety, etc.">
    <a id="search-submit" class="cyan lighten-2 search-by-usage waves-effect waves-light btn">Search</a>
    <div id="drug-data" class="clearfix"></div>
  </div>
<% end %>

app/views/drugs/show.html.erb
<% cache cache_key_for(Drug, "lactmed-show-#{@drug_lact_med.name}") do %>
  <h3 class="margin-top-80"><%= @drug_lact_med.name %></h3>
  <div>
    <%= render partial: 'shared/lact_med_info' %>
    <%= render partial: 'shared/lact_med_drug_details' %>
  </div>
<% end %>

<% cache cache_key_for(Drug, "fda-show-#{@drug_lact_med.name}") do %>
  <div class="margin-top-40 margin-bottom-80">
    <%= render partial: 'shared/fda_info' %>
  </div>
<% end %>

app/views/home/index.html.erb
<% cache("home-quick-search-#{current_date}") do %>
  <%= render partial: 'shared/home_quick_search' %>
<% end %>

<div class="row margin-top-80">
  <% cache("home-recent-searches-#{current_date}") do %>
    <%= render partial: 'shared/home_recent_searches' %>
  <% end %>
  <%= cache "home-common-medications-#{current_date}" do %>
    <%= render partial: 'shared/home_common_meds' %>
  <% end %>
</div>

<% cache("home-search-options-#{current_date}") do %>
  <%= render partial: 'shared/search_options' %>
<% end %>

app/views/shared/_drug_index_summary.html.erb
<% @drugs.each do |drug| %>
  <h3 class="margin-top-40"><%= drug.name %></h3>
  <p><strong>Summary: </strong><%= drug.summary %></p>
  <p><strong>Drug Classes: </strong><%= drug.drug_classes %></p>
  <%= link_to "View More Information", drug_path(name: drug.slug), class: "drug-show-page-link" %>
<% end %>

app/views/shared/_fda_info.html.erb
<h5>Information from the FDA</h5>
<% if @drug_fda == "Not Found" %>
  <p>
    There is no information on <%= @drug_lact_med.name %> from the FDA to display.
  </p>
<% else %>
  <p>
    The information below is provided by OpenFDA, a research project. This data is not
    intended for clinical use. While the FDA makes every effort to ensure the data is accurate,
    you should assume all results are unvalidated.
  </p>
  <p><strong>Nursing Mothers:</strong> <%= @drug_fda.nursing_mothers %></p>
  <p><strong>Drug Description:</strong> <%= @drug_fda.description %></p>
  <p><strong>Usage:</strong> <%= @drug_fda.usage %></p>
  <p><strong>Manufacturer:</strong> <%= @drug_fda.manufacturer_name %></p>
<% end %>

app/views/shared/_home_common_meds.html.erb
<div id="common-medications" class="col s6 center">
  <%= image_tag "baby-2.jpg" %>
  <h5>Common Medications</h5>
  <ul>
    <a href="/drugs/Levothyroxine" class="col s6 center"><li>Levothyroxine (T4)</li></a>
    <a href="/drugs/Simvastatin" class="col s6 center"><li>Simvastatin</li></a>
    <a href="/drugs/Sertraline" class="col s6 center"><li>Sertraline</li></a>
    <a href="/drugs/Amoxicillin" class="col s6 center"><li>Amoxicillin</li></a>
    <a href="/drugs/Metformin" class="col s6 center"><li>Metformin</li></a>
    <a href="/drugs/Azithromycin" class="col s6 center"><li>Azithromycin</li></a>
  </ul>
</div>

app/views/shared/_home_quick_search.html.erb
<% if current_user %>
  <h3 class="margin-top-80 center">Welcome back, <%= current_user.name %>!</h3>
<% else %>
  <h3 class="margin-top-80 center">Welcome to Lactation Station!</h3>
<% end %>
<input type="text" name="drug-name" id="drug-name" placeholder="Amoxicillin, Sertraline, etc.">
<a id="search-submit" class="search-by-name center-button waves-effect waves-light btn btn-large cyan lighten-2">Quick Medication Lookup</a>
<div id="drug-data" class="clearfix"></div>

app/views/shared/_home_recent_searches.html.erb
<div id="recent-searches" class="col s6 center">
  <%= image_tag "baby-1.jpg" %>
  <h5>Recent Searches</h5>
  <ul>
    <% @searches.each do |search| %>
      <li class="col s6 center"><%= link_to search.drug_name, "/drugs/#{search.drug_name}" %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_lact_med_drug_details.html.erb
<p><strong>Summary:</strong> <%= @drug_lact_med.summary %></p>
<p><strong>Drug Levels for Mothers and Infants:</strong> <%= @drug_lact_med.drug_levels %></p>
<p><strong>Effects in Breastfed Infants:</strong> <%= @drug_lact_med.effects_in_breastfed_infants %></p>
<p><strong>Effects on Lactation and Breastmilk:</strong> <%= @drug_lact_med.effects_on_lactation_and_breastmilk %></p>
<p><strong>Drug Classes:</strong> <%= @drug_lact_med.drug_classes %></p>

app/views/shared/_lact_med_info.html.erb
<h5>Information from LactMed</h5>
<p>
  The information below comes from the Drugs and Lactation Database (LactMed),
  a database of drugs and chemicals from the National Institutes of Health (NIH).

  All data are derived from fully-referenced, peer-reviewed scientific literature.

  For even more information about <%= @drug_lact_med.name %> according to the NIH,
  visit <%= link_to "LactMed", "http://toxnet.nlm.nih.gov/newtoxnet/lactmed.htm" %>.
</p>

app/views/shared/_lact_med_reference.html.erb
<div class="margin-top-80">
  <h5>Information from LactMed</h5>
  <p>The information below comes from the Drugs and Lactation Database (LactMed),
    a database of drugs and chemicals from the National Institutes of Health (NIH).
    All data are derived from fully-referenced, peer-reviewed scientific literature.
    For even more information according to the NIH, visit
    <%= link_to "LactMed", "http://toxnet.nlm.nih.gov/newtoxnet/lactmed.htm" %>.
  </p>
</div>

app/views/shared/_navbar.html.erb
<nav id="primary-navigation">
  <div class="nav-wrapper amber darken-2">
    <%= cache "logo-navbar-#{current_date}" do %>
      <a href="/" class="brand-logo side-margin-15 white-text">LactationStation</a>
    <% end %>
    <ul id="nav-mobile" class="right hide-on-med-and-down offset-s1 white-text">
      <% if current_user %>
        <%= cache "logout-navbar-#{current_user}" do %>
          <li><%= link_to "Home", home_index_path %></li>
          <li><%= link_to "Search", drugs_search_name_path %></li>
          <li><%= link_to "All Medications", drugs_path %></li>
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Logout", logout_path %></li>
        <% end %>
      <% else %>
        <%= cache "login-navbar-#{current_date}" do %>
          <li><%= link_to "Login with Twitter", login_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_search_options.html.erb
<div class="row margin-top-80 margin-bottom-80">
  <div id="search-by-name" class="col s4 center">
    <%= image_tag "baby-3.jpg", alt:"cute baby", class:"width-250" %>
    <h5>Search By Name</h5>
    <p>
      Best for moms who know what medication they're looking for.
    </p>
    <div class="center-button width-150 waves-effect waves-light btn cyan lighten-2">
      <%= button_to "Search", drugs_search_name_path, method: 'get' %>
    </div>
  </div>
  <div id="search-by-cause" class="col s4 center">
    <%= image_tag "baby-4.jpg", alt:"cute baby", class:"width-250" %>
    <h5>Search By Cause</h5>
    <p>
      Check out your options based on what you're seeking medication for.
    </p>
    <div class="center-button width-150 waves-effect waves-light btn cyan lighten-2">
      <%= button_to "Search", drugs_search_usage_path, method: 'get' %>
    </div>
  </div>
  <div id="all-medications" class="col s4 center">
    <%= image_tag "baby-5.jpg", alt:"cute baby", class:"width-250" %>
    <h5>View All Medications</h5>
    <p>
      Just browsing? Browse all the medications listed by name.
    </p>
    <div class="center-button width-150 waves-effect waves-light btn cyan lighten-2">
      <%= button_to "View All", drugs_path, method: 'get' %>
    </div>
  </div>
</div>

app/views/shared/_timeline.html.erb
<div id="recentTweets" class="margin-bottom-80">
  <h5 class="margin-top-80 margin-bottom-25">Recent Tweets About Breastfeeding</h5>
  <% current_user.breastfeeding_timeline.each do |tweet| %>
    <div class="">
      <div class="col 2">
        <img class="timelinePhoto" src='<%= tweet.user.profile_image_uri %>'>
      </div>
      <div class="col 8 width80 margin-bottom-25">
        <p class="timelineTweetText"><strong><%= tweet.user.name %></strong> (@<%= tweet.user.screen_name %>)</p>
        <p><%= tweet.text %></p>
        <%= link_to "View on Twitter", "https://twitter.com/#{tweet.user.screen_name}", class:"right", target:"_blank" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_tweet_form.html.erb
<% if current_user %>
  <%= cache "twitter-user-info-#{current_user}" do %>
    <div class="margin-bottom-50" id="status-form">
      <%= form_tag("/status", method: "post") do %>
        <div class="flow-text">
          <%= text_area_tag(:tweet, "", size: "800x80", placeholder: "Share your thoughts on breastfeeding.") %>
        </div>
        <div class="right waves-effect waves-light btn cyan lighten-2">
          <%= submit_tag "Tweet" %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<% if current_user %>
  <%= cache "twitter-tweet-form-#{current_user}" do %>
    <img id="profile-photo" src='<%= current_user.profile_photo %>'>
    <h2 class="zero-margin-bottom"><%= current_user.name %></h2>
    <p class="light-grey-text">@<%= current_user.handle %></p>
  <% end %>
<% end %>

app/views/shared/_welcome_pitch.html.erb
<h3 class="margin-top-80 center">Your baby's safety is our priority</h3>
<%= image_tag "baby-homepage.jpg", class:"center-element" %>
<h5 class="center" >Find out which medications are safe to take while breastfeeding</h5>
<div class="center">
  <p>Breastfeeding is challenging enough. Trying to figure out which medications are safe for you
  and for your baby? That's more than you should have to handle. At LactationStation, you can quickly find information about specific drugs your
  doctor may prescribe. We pull from two sources: <a href="http://toxnet.nlm.nih.gov/newtoxnet/lactmed.htm">LactMed</a>,
  a database from the National Institutes of Health (NIH) that specializes in
  research regarding lactation and the Federal Drug Administration (FDA),
  which provides detailed information on specific medications.</p>

  <p>You can search for medications by <%= link_to "name", drugs_search_name_path %> or <%= link_to "indication", drugs_search_usage_path %>. Or you can
  <%= link_to "view a comprehensive list of over 1000 medications", drugs_path %>.</p>
</div>

app/views/welcome/index.html.erb
<div class="margin-bottom-80">
  <% cache("welcome-twitter-cta-#{current_date}") do %>
    <%= render partial: 'shared/welcome_pitch' %>
  <% end %>

  <div class="center-button waves-effect waves-light btn-large cyan lighten-2">
    <% if current_user %>
      <%= cache "home-search-medication-button-#{current_user}" do %>
        <%= button_to "Search Medications", drugs_search_name_path, method: 'get' %>
      <% end %>
    <% else %>
      <%= cache "home-twitter-login-button-#{current_date}" do %>
        <%= button_to "Login with Twitter", login_path %>
      <% end %>
    <% end %>
  </div>
</div>